// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RoomBookingBackend.Data;

#nullable disable

namespace room_booking_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260210181414_SeedInitialBookingsUpdate")]
    partial class SeedInitialBookingsUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RoomBookingBackend.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 10, 18, 14, 14, 167, DateTimeKind.Utc).AddTicks(6284),
                            EndTime = new DateTime(2026, 2, 11, 3, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Purpose = "Workshop UI/UX",
                            RoomId = 1,
                            StartTime = new DateTime(2026, 2, 11, 1, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Selesai",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 10, 18, 14, 14, 167, DateTimeKind.Utc).AddTicks(6311),
                            EndTime = new DateTime(2026, 2, 12, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Purpose = "Pameran PENSASI & Beasiswa Study Aboard",
                            RoomId = 2,
                            StartTime = new DateTime(2026, 2, 12, 6, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Pending",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("RoomBookingBackend.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Facilities")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 50,
                            Facilities = "Sound System, Projector, Meja, Kursih, AC",
                            IsAvailable = true,
                            IsDeleted = false,
                            Location = "Gedung D3 Lantai 1",
                            Name = "Mini Theater D3"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 200,
                            Facilities = " LED Display/Videotron, Sound System, Projector, Meja, Kursih, AC",
                            IsAvailable = true,
                            IsDeleted = false,
                            Location = "Lt.6 Gedung Pasca Sarjana",
                            Name = "Auditorium Gedung Pasca Sarjana"
                        });
                });

            modelBuilder.Entity("RoomBookingBackend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@gmail.com",
                            FullName = "Admin1",
                            PasswordHash = "$2a$11$L1gcQKHTzIAIraON.575GOYlsqfFcWhu5raU8YKTGkKRg4k/OdVsa",
                            PhoneNumber = "081122334455",
                            Position = "Admin",
                            Username = "adminku"
                        });
                });

            modelBuilder.Entity("RoomBookingBackend.Models.Booking", b =>
                {
                    b.HasOne("RoomBookingBackend.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RoomBookingBackend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
